US-03 Unir los campos del vídeo en un único string - Transformar el string que contiene todos los campos del vídeo a una representación vectorial haciendo uso de sentence-transformers
PedroChaparro/PI202202-alako-data pull request #29
Opened 2022-08-27 23:10 UTC by andres123dbh

Entrego un nootbook que se encarga de unir y volver en vector los strings con un modelo multilingüe, además de los archivos donde se almacenan, aclaro que debido a que los archivos json se pasaban del límite por lo tanto los comprimí en un zip

2022-08-28 01:06 UTC, PedroChaparro requested changes
@andres123dbh En este caso se puede descomprimir el `.zip` y reemplazar los `.json `existentes por los nuevos que usted generó para evitar duplicidad y "peso" innecesario. **(No había visto la descripción del PullRequest cuando puse este mensaje pero creo que es importante definir qué se va a hacer al respecto).**

2022-08-28 01:08 UTC, PedroChaparro requested changes
@andres123dbh en los nuevos .json solo está el vector de los vídeos, deberían estar todos los demás datos con el fín de enviarlos al front-end.

2022-08-28 17:07 UTC, PedroChaparro commented on data-cleaning/join_vectorize.ipynb
> +    "    video_texts_data_nostopwords = data_nostopwords_frame['title'][data_index] + data_nostopwords_frame['description'][data_index] + data_nostopwords_frame['tags'][data_index]\n",
Acá se podría agregar un espacio `" "` entre cada columna para evitar perder las últimas / primeras palabras de cada campo.

2022-08-28 17:33 UTC, andres123dbh commented on data-cleaning/join_vectorize.ipynb
> +    "    video_texts_data_nostopwords = data_nostopwords_frame['title'][data_index] + data_nostopwords_frame['description'][data_index] + data_nostopwords_frame['tags'][data_index]\n",
Agregado

2022-08-28 19:23 UTC, PedroChaparro approved these changes
@Woynert, ¿Dejamos los datos en el .zip? Veo que cada uno terminó pesando más de 100MB que es el límite de Github.

2022-08-28 19:45 UTC, SilviaPabon commented
> @andres123dbh en los nuevos .json solo está el vector de los vídeos, deberían estar todos los demás datos con el fín de enviarlos al front-end.

Teniendo los comentarios del compañero Pedro, comento lo siguiente, @andres123dbh:
- Interesante saber eso de GitHub, que tiene un límite, podrían dejarse en ese caso comprimidos, o podría dividirse en varios archivos, o leí que existe una cosa que se llama Git Large File Storage, que podríamos poner también en consideración, espero a ver qué opinan @Woynert y @PedroChaparro.
- No deberían dejarse como punto de referencia los anteriores archivos .json 🤔 o es innecesario? (Pregunto por curiosidad)

2022-08-28 20:04 UTC, PedroChaparro commented
> * Interesante saber eso de GitHub, que tiene un límite, podrían dejarse en ese caso comprimidos, o podría dividirse en varios archivos, o leí que existe una cosa que se llama Git Large File Storage, que podríamos poner también en consideración, espero a ver qué opinan @Woynert y @PedroChaparro.

No lo conocía, pero como sea más sencillo, en este caso solo es clonar el repositorio en la MV y descomprimir el archivo. Espero a ver qué otra alternativas podríamos considerar, inclusó pensé en subirlo a Drive o algún servicio de ese tipo y poner solo las URL acá, pero no sé qué sea más factible. 

> * No deberían dejarse como punto de referencia los anteriores archivos .json thinking o es innecesario? (Pregunto por curiosidad)

Es bueno por tener el punto de referencia, pero considero que habría duplicidad y el repositorio quedaría más pesado de lo necesario.

2022-08-28 20:12 UTC, SilviaPabon commented
> No lo conocía, pero como sea más sencillo, en este caso solo es clonar el repositorio en la MV y descomprimir el archivo. Espero a ver qué otra alternativas podríamos considerar, inclusó pensé en subirlo a Drive o algún servicio de ese tipo y poner solo las URL acá, pero no sé qué sea más factible.

Diría que, o lo dejamos comprimido, por mí está bien, o lo de Drive también, por mantener un orden, y no haya problemas con lo del tamaño, también puede ser. Quizá eso de Git Large File, sea un complique, pero bueno saber que existe.

2022-08-28 22:25 UTC, Woynert requested changes
Mi opinión es que ya que estamos trabajando con "Big data" No es sorpresa que los archivos puedan ser pesados. Si vamos a guardarlo en github me parece razonable tenerlo comprimido. Y en caso de que fuese incluso más grande, comprimirlo en varias partes.
El formato es importante, __rar__ es un formato propietario, no tenemos licencia y no está instalado por defecto en servidores. __zip__ es libre pero para descomprimirlo se requiere un paquete extra. Propongo que se emplee __tar.gz__ que es un formato de compresión nativo en muchos sistemas operativos linux, incluyendo debían que estamos usando.

2022-08-28 23:02 UTC, SilviaPabon commented
> Mi opinión es que ya que estamos trabajando con "Big data" No es sorpresa que los archivos puedan ser pesados. Si vamos a guardarlo en github me parece razonable tenerlo comprimido. Y en caso de que fuese incluso más grande, comprimirlo en varias partes. El formato es importante, **rar** es un formato propietario, no tenemos licencia y no está instalado por defecto en servidores. **zip** es libre pero para descomprimirlo se requiere un paquete extra. Propongo que se emplee **tar.gz** que es un formato de compresión nativo en muchos sistemas operativos linux, incluyendo debían que estamos usando.

Vaya, buenísimos estos datos. Entonces con base en esto, @andres123dbh haz la respectiva comprensión al formato dicho por @Woynert, para aceptar el PR. Estuve chismoseando y 7-Zip o PeaZip te permiten hacer la compresión.

2022-08-29 00:08 UTC, Woynert approved these changes

2022-08-29 00:26 UTC, SilviaPabon approved these changes

2022-08-29 00:27 UTC, merged