Scrapper data silvia
PedroChaparro/PI202202-alako-data pull request #3
Opened 2022-08-02 13:58 UTC by SilviaPabon

Scrapper con Python creado. Quedo pendiente para cualquier corrección o mejora-

2022-08-10 16:09 UTC, PedroChaparro requested changes
No se está tomando la descripción completa de los vídeos, llega a un límite de caracteres (al parecer 156) y se muestran puntos suspensivos.

2022-08-10 16:23 UTC, PedroChaparro commented
@SilviaPabon me parecería útil que se muestre un mensaje (como en los otros dos scrapers) indicando cuando la obtención de datos de cada video ha finalizado y cuando comience el scraping en una nueva búsqueda.

2022-08-10 16:56 UTC, SilviaPabon commented
> @SilviaPabon me parecería útil que se muestre un mensaje (como en los otros dos scrapers) indicando cuando la obtención de datos de cada video ha finalizado y cuando comience el scraping en una nueva búsqueda.

Copy that!

2022-08-10 16:59 UTC, Woynert commented
Algunas observaciones:

- Existe `scrapper.py` y `scrapper2.py` no queda claro cual deberia usar.
- `scrapper.py` da un error por paquete faltante `lxml` que no está especificado en la documentación.
- La libreria usada es solo compatible con versiones de chrome/chromium mayores o iguales a 104 (lo digo porque es una version muy reciente y que no todos podrian haber actualizado, pues salió el 2 de agosto) y no esta especificado.
- Como comentó @PedroChaparro las descripciones están cortadas.

2022-08-10 17:25 UTC, PedroChaparro commented
> Algunas observaciones:
> 
> * Existe `scrapper.py` y `scrapper2.py` no queda claro cual deberia usar.
> * `scrapper.py` da un error por paquete faltante `lxml` que no está especificado en la documentación.
> * La libreria usada es solo compatible con versiones de chrome/chromium mayores o iguales a 104 (lo digo porque es una version muy reciente y que no todos podrian haber actualizado, pues salió el 2 de agosto) y no esta especificado.
> * Como comentó @PedroChaparro las descripciones están cortadas.

@SilviaPabon en cuanto a las dos versiones, si aportan algo muy diferente pienso que es buena idea mantenerlas, pero si los cambios son muy pocos diría que se puede usar una sola versión. Sobre los paquetes ya le di mi sugerencia.

2022-08-11 05:56 UTC, SilviaPabon commented
> @SilviaPabon, no se está tomando la descripción completa de los vídeos, llega a un límite de caracteres (al parecer 156) y se muestran puntos suspensivos.

Corregido

> @SilviaPabon me parecería útil que se muestre un mensaje (como en los otros dos scrapers) indicando cuando la obtención de datos de cada video ha finalizado y cuando comience el scraping en una nueva búsqueda.

Hecho

> Algunas observaciones:
> 
> * Existe `scrapper.py` y `scrapper2.py` no queda claro cual deberia usar. 

Dejé sólo scrapper.py la diferencia estaba en que uno tenía un for adicional dentro de una función, pero ambos demoran lo mismo.

> * `scrapper.py` da un error por paquete faltante `lxml` que no está especificado en la documentación.

Si sigue ocurriendo borra el parámetro features='lxml' de las líneas indicadas en el README. A mí me pedía colocarlo, que si no lo hacia y alguien más lo ejecutaba podía ponerse otra opción por defecto.

> * La libreria usada es solo compatible con versiones de chrome/chromium mayores o iguales a 104 (lo digo porque es una version muy reciente y que no todos podrian haber actualizado, pues salió el 2 de agosto) y no esta especificado. Interesante dato.
> * Como comentó @PedroChaparro las descripciones están cortadas.

Corregido.

2022-08-11 15:52 UTC, PedroChaparro requested changes
@SilviaPabon en la descripción de los vídeos ahora aparecen `"\\n"` y veo también algunos `"\\\". También me está dando problema el lxml que mencionó Whayner, me parece raro que el pip freeze no lo hubiera agregado como dependencia si estaba instalado en su Venv, pienso que lo podría agregar manualmente o estaría bien dejar esa anotación en el readme.

2022-08-11 16:00 UTC, PedroChaparro commented on scraper-data-silvia/scrapper.py
> +with open('./scraper-data-silvia/data.json', 'w+', encoding='utf8') as json_file:
Esta línea me da error ya que intenta buscar otra carpeta `./scraper-data-silvia` dentro de la misma carpeta.

2022-08-13 21:11 UTC, SilviaPabon commented
> @SilviaPabon en la descripción de los vídeos ahora aparecen `"\\n"` y veo también algunos `"\\\"`. También me está dando problema el lxml que mencionó Whayner, me parece raro que el pip freeze no lo hubiera agregado como dependencia si estaba instalado en su Venv, pienso que lo podría agregar manualmente o estaría bien dejar esa anotación en el readme.

Traté de mejorarle la limpieza, me estuvo tomando literalmente todo como string y cuando creí que los borraba, pues no, porque no habían line breaks sino strings que representaban los saltos de línea. Eso sí, quedaron caracteres tipo \0026 que representan al & creo, y otros, que no supe cómo hacer para que mostrara normal el & o el caracter correspondiente. Adicioné la versión utilizada de lxml a los requirements.

2022-08-13 21:11 UTC, SilviaPabon commented on scraper-data-silvia/scrapper.py
> +with open('./scraper-data-silvia/data.json', 'w+', encoding='utf8') as json_file:
Probé luego de hacer unos cambios, tanto en Linux como en Windows y me funciona. Espero a uds igual.

2022-08-13 21:50 UTC, PedroChaparro commented on scraper-data-silvia/scrapper.py
> +with open('./scraper-data-silvia/data.json', 'w+', encoding='utf8') as json_file:
![image](https://user-images.githubusercontent.com/62714297/184511825-3a0c73e4-85f8-4280-9546-0b325da9f9bd.png)

Funciona si lo cambio a `Path(".\data.json")` que es la ruta relativa desde el scraper.py al data.json.

2022-08-13 21:57 UTC, SilviaPabon commented on scraper-data-silvia/scrapper.py
> +with open('./scraper-data-silvia/data.json', 'w+', encoding='utf8') as json_file:
Lo loco es que si ponía eso, el data.json lo ponía en la carpeta PI2022... Así que...

2022-08-13 22:06 UTC, PedroChaparro commented on scraper-data-silvia/scrapper.py
> +with open('./scraper-data-silvia/data.json', 'w+', encoding='utf8') as json_file:
Porque usted lo está ejecutando desde la raíz del proyecto, lo cual no se especifica en el README, considero importante o agregarlo al README o realizar el cambio de la ruta relativa.

2022-08-13 23:52 UTC, PedroChaparro approved these changes

2022-08-17 17:48 UTC, SilviaPabon commented
@Woynert y @andres123dbh recurden aceptar este PR. Gracias!

2022-08-17 18:15 UTC, andres123dbh approved these changes

2022-08-17 20:43 UTC, Woynert approved these changes

2022-08-17 20:43 UTC, merged